### ISSUE TITLE
Comandos específicos de Windows

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-gran_casino_etsidi#3]
En vuestro código empleáis llamadas a [comandos específicos de Windows](https://github.com/aigora/twE105_1920-gran_casino_etsidi/blob/d20afdf7689d382fa48b6f672b5337bd2e1ea3f1/men%C3%BA%20usuario.c#L7). Esto hace que vuestro código no sea portable, es decir, no se puede compilar o ejecutar en otros sistemas operativos. 
En particular, las pruebas de código tras la entrega final se harán con sistema automático que trabaja en Linux, debéis evitar estas llamadas.

**Comment by idopazo** [comment]
Hola Oscar
¿Sería mejor suprimir esas lineas de código, adaptarlas a Linux, o, si se puede, buscar otra alternativa que genere un resultado parecido?

**Comment by oscarperpinan** [comment]
En general, cada sistema operativo tiene formas diferentes de realizar esas operaciones. Si encontráis soluciones generales, perfecto, pero en caso contrario es mejor eliminarlos.
